blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/AOSSIE-Org/Devr.AI/discussions
    about: Ask questions, share ideas, and discuss with the community

  - name: 📚 Documentation
    url: https://github.com/AOSSIE-Org/Devr.AI/blob/main/README.md
    about: Check the documentation for setup guides and API references
  
  - name: 🆘 Discord Support
    url: https://discord.gg/BjaG8DJx2G
    about: Get help from the community on our Discord server

  - name: 🔒 Security Issues
    url: https://github.com/AOSSIE-Org/Devr.AI/security/advisories/new
    about: Report security vulnerabilities privately
