[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[plugins]]
package = "@netlify/plugin-functions"

[dev]
command = "npm run dev"
port = 3001
publish = "dist"
